from app.services.parser import looks_like_preamble, read_enquiry_file, split_enquiries

SEPARATOR = "-" * 80

TWO_ENQUIRIES = f"""SAMPLE ENQUIRIES
Use this file as test data. Enquiries are separated by a line of dashes.
{SEPARATOR}
From: Rachel Whitfield
Email: r.whitfield@northgate-logistics.co.uk
Message:
Hi, we need a web app. Budget is around £40,000.
{SEPARATOR}
From: Deniz
Email: deniz@zora-protocol.xyz
Message:
Need smart contracts. Budget flexible.
"""


def test_split_enquiries_drops_preamble_and_separators():
    chunks = split_enquiries(TWO_ENQUIRIES)
    assert len(chunks) == 2
    assert "Rachel Whitfield" in chunks[0]
    assert "Deniz" in chunks[1]
    assert "SAMPLE ENQUIRIES" not in chunks[0]


def test_split_enquiries_no_preamble_when_message_present():
    text = f"""From: A
Email: a@example.com
Message:
Hello
{SEPARATOR}
From: B
Email: b@example.com
Message:
World
"""
    chunks = split_enquiries(text)
    assert len(chunks) == 2


def test_looks_like_preamble():
    assert looks_like_preamble("SAMPLE ENQUIRIES — Sodio Task\nDo not edit this file.")
    assert not looks_like_preamble("From: Rachel\nEmail: r@x.co\nMessage:\nHi")


def test_read_enquiry_file_decodes_bytes():
    chunks = read_enquiry_file(TWO_ENQUIRIES.encode("utf-8"))
    assert len(chunks) == 2
